[package]
name = "viman"
version = "0.1.0"
edition = "2021"


[dependencies]
argonautica = "0.2.0"
diesel = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15"
serde = "1.0.183"

[dependencies.rocket]
version = "=0.5.0-rc.3"
features = ["json"]

[profile.dev]
debug = true
